export const environment = {
    production: true,

    apiHost: 'http://13.127.24.123/vizza/api/index.php/v1/',
    apiHostTravel: 'http://13.127.24.123/vizza/api/index.php/travel/',
    apiHostPa: 'http://13.127.24.123/vizza/api/index.php/pa/',
    apiHostHealth: 'http://13.127.24.123/vizza/api/index.php/health/',
    apiHostHome: 'http://13.127.24.123/vizza/api/index.php/home/',
    apiHostPos: 'http://13.127.24.123/vizza/api/index.php/pos/',
    apiHostDm: 'http://13.127.24.123/vizza/api/index.php/dm/',
    apiHostMotor: 'http://13.127.24.123/vizza/api/index.php/mtw/',
    apiHostMotorFour: 'http://13.127.24.123/vizza/api/index.php/mfw/',
    apiHostLife: 'http://13.127.24.123/vizza/api/index.php/endowment/',
    apiHostTerm: 'http://13.127.24.123/vizza/api/index.php/termlife/',
    apiHostmiscproduct: 'http://13.127.24.123/vizza/api/index.php/misc_product/',
    webHost: 'http://13.127.24.123',
    imgUrl: 'http://13.127.24.123/vizza',
    travelInsurance: true,
    healthInsurance: true,
    lifeInsurance: true,
    motorInsurance: true,
    paAccident: true
    //
    // apiHost: 'https://vizzainsurance.com/vizza/api/index.php/v1/',
    // apiHostTravel: 'https://vizzainsurance.com/vizza/api/index.php/travel/',
    // apiHostPa: 'https://vizzainsurance.com/vizza/api/index.php/pa/',
    // apiHostHealth: 'https://vizzainsurance.com/vizza/api/index.php/health/',
    // apiHostHome: 'https://vizzainsurance.com/vizza/api/index.php/home/',
    // apiHostPos: 'https://vizzainsurance.com/vizza/api/index.php/pos/',
    // apiHostDm: 'https://vizzainsurance.com/vizza/api/index.php/dm/',
    // apiHostLife: 'https://vizzainsurance.com/vizza/api/index.php/endowment/',
    // apiHostTerm: 'https://vizzainsurance.com/vizza/api/index.php/termlife/',
    // apiHostMotor: 'http://vizzainsurance.com/vizza/api/index.php/mtw/',
    // apiHostMotorFour: 'http://vizzainsurance.com/vizza/api/index.php/mtw/',
    // apiHostmiscproduct: 'http://vizzainsurance.com/vizza/api/index.php/misc_product/',
    // webHost: 'https://vizzainsurance.com',
    // imgUrl: 'https://vizzainsurance.com/vizza',
    // travelInsurance: true,
    // healthInsurance: true,
    // lifeInsurance: false,
    // motorInsurance: false,
    // paAccident: true

};

